// Test generated by RoostGPT for test golang-level0-JobSchd using AI Type Open AI and AI Model gpt-4-1106-preview

package main

import (
	"testing"
	"strings"
)

// Assuming sayHelloTo is a function that takes a string argument and returns a string.
// func sayHelloTo(name string) string {
//     // implementation here
// }

func TestSayHelloTo_Positive(t *testing.T) {
    // Positive case
    name := "World"
    want := "Hello, World"
    
    got := sayHelloTo(name)
    if got != want {
        t.Errorf("sayHelloTo(%q) = %q, want %q", name, got, want)
    }
}

func TestSayHelloTo_Negative(t *testing.T) {
    // Negative case
    name := ""
    wantContain := "Hello"
    
    got := sayHelloTo(name)
    if !strings.Contains(got, wantContain) {
        t.Errorf("sayHelloTo(%q) should contain %q, got %q", name, wantContain, got)
    }
}

