// Test generated by RoostGPT for test golang-level0-JobSchd using AI Type Open AI and AI Model gpt-4-1106-preview

package scheduler

import (
    "testing"
)

// Positive test case
func TestSayHelloTo_Positive(t *testing.T) {
    name := "World"
    expected := "Hello, World!" // Assuming this is what sayHelloTo should return
    result := sayHelloTo(name)

    if result != expected {
        t.Errorf("sayHelloTo(%s) = %v; want %v", name, result, expected)
    }
}

// Negative test case
func TestSayHelloTo_Negative(t *testing.T) {
    name := "" // Assuming an empty name is not allowed and should return an error
    _, err := sayHelloTo(name)

    if err == nil {
        t.Errorf("sayHelloTo(%s) did not return an error; want error for empty name", name)
    }
}

