// Test generated by RoostGPT for test golang-level0-JobSchd using AI Type Open AI and AI Model gpt-4

package main

import (
	"bytes"
	"testing"
)

func TestSayHelloTo(t *testing.T) {
	tt := []struct {
		name   string
		input  string
		output string
	}{
		{name: "Empty string", input: "", output: "Hello \n"},
		{name: "Non-empty string", input: "John", output: "Hello John\n"},
	}

	for _, tc := range tt {
		t.Run(tc.name, func(t *testing.T) {
			var buf bytes.Buffer
			sayHelloTo(tc.input)
			got := buf.String()
			if got != tc.output {
				t.Errorf("Expected: %q, got: %q", tc.output, got)
			}
		})
	}
}
