// Test generated by RoostGPT for test golang-level0-JobSchd using AI Type Open AI and AI Model gpt-4

package main

import (
	"os"
	"strings"
	"testing"
)

func TestSayHelloTo(t *testing.T) {
	tt := []struct {
		name   string
		input  string
		output string
	}{
		{name: "Empty string", input: "", output: "Hello"},
		{name: "Non-empty string", input: "John", output: "HelloJohn"},
	}

	for _, tc := range tt {
		t.Run(tc.name, func(t *testing.T) {
			// var buf bytes.Buffer
			r, w, _ := os.Pipe()
			os.Stdout = w

			// Capture the output in a goroutine
			output := make(chan string)
			go func() {
				buf := make([]byte, len(tc.output))
				_, _ = r.Read(buf)
				output <- string(buf)
			}()
			sayHelloTo(tc.input)
			// got := buf.String()
			w.Close()
			result := <-output
			result = strings.TrimSpace(result)
			if result != tc.output {
				t.Errorf("Expected: %q, got: %q", tc.output, result)
			}
		})
	}
}
