// Test generated by RoostGPT for test golang-level0-PassGen using AI Type Open AI and AI Model gpt-4-1106-preview

package main

import (
	"testing"
)

func TestGeneratePassword_Positive(t *testing.T) {
	length := 10 // Example length for the test
	pass := generatePassword(length)
	if len(pass) != length {
		t.Errorf("Expected password of length %d, got %d", length, len(pass))
	}
}

func TestGeneratePassword_Negative(t *testing.T) {
	length := -1
	pass := generatePassword(length)
	if len(pass) != 0 {
		t.Errorf("Expected empty password for negative length, got %s", pass)
	}
}

