// Test generated by RoostGPT for test golang-level0-PassGen using AI Type Open AI and AI Model gpt-4

package main

import (
	"strings"
	"testing"
)

func TestGeneratePassword(t *testing.T) {
	tests := []struct {
		name     string
		length   int
		expected int
	}{
		{"Password length 8", 8, 8},
		{"Password length 10", 10, 10},
		{"Password length 12", 12, 12},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := generatePassword(tt.length)
			if len(got) != tt.expected {
				t.Errorf("generatePassword() = %v, want %v", len(got), tt.expected)
			}

			digits := "0123456789"
			specials := "~=+%^*/()[]{}/!@#$?|"
			if !strings.ContainsAny(got, digits) {
				t.Errorf("Password does not contain any digit")
			}
			if !strings.ContainsAny(got, specials) {
				t.Errorf("Password does not contain any special character")
			}
		})
	}
}
