// Test generated by RoostGPT for test golang-level0-PassGen using AI Type Open AI and AI Model gpt-4

package main

import (
	"fmt"
	"math/rand"
	"strings"
	"testing"
	"time"
)

func generateTestPassword(n int) string {
	rand.Seed(time.Now().UnixNano())
	chars := []rune("ABCDEFGHIJKLMNOPQRSTUVWXYZ" +
		"abcdefghijklmnopqrstuvwxyz" +
		"0123456789")

	length := n
	var b strings.Builder
	for i := 0; i < length; i++ {
		b.WriteRune(chars[rand.Intn(len(chars))])
	}
	str := b.String()
	return str
}

func TestGeneratePassword(t *testing.T) {
	tests := []struct {
		name string
		n    int
	}{
		{name: "Test length 10", n: 10},
		{name: "Test length 5", n: 5},
		{name: "Test length 0", n: 0},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := generateTestPassword(tt.n)
			if len(got) != tt.n {
				t.Errorf("generatePassword() = %v, want %v", len(got), tt.n)
			}
		})
	}
}

func ExampleMain() {
	password := generateTestPassword(10)
	fmt.Println(password)
}
